"""add ingestion logs and source health

Revision ID: 13f0c307c190
Revises: 52a06567b1e6
Create Date: 2026-09-24 17:43:30.887562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13f0c307c190'
down_revision: Union[str, Sequence[str], None] = '52a06567b1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso_code', sa.String(length=10), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('subregion', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_is_active'), 'countries', ['is_active'], unique=False)
    op.create_index(op.f('ix_countries_iso_code'), 'countries', ['iso_code'], unique=True)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_index(op.f('ix_countries_region'), 'countries', ['region'], unique=False)
    op.create_index(op.f('ix_countries_subregion'), 'countries', ['subregion'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('headline', sa.String(length=1000), nullable=False),
    sa.Column('canonical_url', sa.String(length=2000), nullable=False),
    sa.Column('original_url', sa.String(length=2000), nullable=True),
    sa.Column('author', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('normalized_title_hash', sa.String(length=128), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'canonical_url', name='uq_article_source_canonical_url')
    )
    op.create_index(op.f('ix_articles_collected_at'), 'articles', ['collected_at'], unique=False)
    op.create_index(op.f('ix_articles_content_hash'), 'articles', ['content_hash'], unique=False)
    op.create_index(op.f('ix_articles_country'), 'articles', ['country'], unique=False)
    op.create_index(op.f('ix_articles_headline'), 'articles', ['headline'], unique=False)
    op.create_index(op.f('ix_articles_language'), 'articles', ['language'], unique=False)
    op.create_index(op.f('ix_articles_normalized_title_hash'), 'articles', ['normalized_title_hash'], unique=False)
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_articles_region'), 'articles', ['region'], unique=False)
    op.create_index(op.f('ix_articles_source_id'), 'articles', ['source_id'], unique=False)
    op.create_table('ingestion_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('articles_found', sa.Integer(), nullable=False),
    sa.Column('articles_added', sa.Integer(), nullable=False),
    sa.Column('articles_skipped', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_logs_source_id'), 'ingestion_logs', ['source_id'], unique=False)
    op.create_index(op.f('ix_ingestion_logs_status'), 'ingestion_logs', ['status'], unique=False)
    op.create_table('source_health',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('total_attempts', sa.Integer(), nullable=False),
    sa.Column('successful_attempts', sa.Integer(), nullable=False),
    sa.Column('last_status_code', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_health_source_id'), 'source_health', ['source_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_health_source_id'), table_name='source_health')
    op.drop_table('source_health')
    op.drop_index(op.f('ix_ingestion_logs_status'), table_name='ingestion_logs')
    op.drop_index(op.f('ix_ingestion_logs_source_id'), table_name='ingestion_logs')
    op.drop_table('ingestion_logs')
    op.drop_index(op.f('ix_articles_source_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_region'), table_name='articles')
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_normalized_title_hash'), table_name='articles')
    op.drop_index(op.f('ix_articles_language'), table_name='articles')
    op.drop_index(op.f('ix_articles_headline'), table_name='articles')
    op.drop_index(op.f('ix_articles_country'), table_name='articles')
    op.drop_index(op.f('ix_articles_content_hash'), table_name='articles')
    op.drop_index(op.f('ix_articles_collected_at'), table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_countries_subregion'), table_name='countries')
    op.drop_index(op.f('ix_countries_region'), table_name='countries')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_iso_code'), table_name='countries')
    op.drop_index(op.f('ix_countries_is_active'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
