"""create news intelligence tables

Revision ID: 9ba0a79cdccb
Revises: d530ed78fe00
Create Date: 2026-09-24 17:48:14.959653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ba0a79cdccb'
down_revision: Union[str, Sequence[str], None] = 'd530ed78fe00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'entity_type', name='uq_entity_name_type')
    )
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_topic_name')
    )
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    op.create_table('analytical_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('conflict_score', sa.Float(), nullable=False),
    sa.Column('geopolitical_score', sa.Float(), nullable=False),
    sa.Column('economic_score', sa.Float(), nullable=False),
    sa.Column('technology_score', sa.Float(), nullable=False),
    sa.Column('climate_score', sa.Float(), nullable=False),
    sa.Column('wellness_score', sa.Float(), nullable=False),
    sa.Column('classification', sa.String(length=100), nullable=True),
    sa.Column('evidence_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytical_scores_article_id'), 'analytical_scores', ['article_id'], unique=True)
    op.create_table('article_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'category_id', name='uq_article_category')
    )
    op.create_index(op.f('ix_article_categories_article_id'), 'article_categories', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_categories_category_id'), 'article_categories', ['category_id'], unique=False)
    op.create_table('article_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'entity_id', name='uq_article_entity')
    )
    op.create_index(op.f('ix_article_entities_article_id'), 'article_entities', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_entities_entity_id'), 'article_entities', ['entity_id'], unique=False)
    op.create_table('article_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'topic_id', name='uq_article_topic')
    )
    op.create_index(op.f('ix_article_topics_article_id'), 'article_topics', ['article_id'], unique=False)
    op.create_index(op.f('ix_article_topics_topic_id'), 'article_topics', ['topic_id'], unique=False)
    op.create_table('one_line_news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('one_line', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_one_line_news_article_id'), 'one_line_news', ['article_id'], unique=True)
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('summary_method', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_article_id'), 'summaries', ['article_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summaries_article_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_one_line_news_article_id'), table_name='one_line_news')
    op.drop_table('one_line_news')
    op.drop_index(op.f('ix_article_topics_topic_id'), table_name='article_topics')
    op.drop_index(op.f('ix_article_topics_article_id'), table_name='article_topics')
    op.drop_table('article_topics')
    op.drop_index(op.f('ix_article_entities_entity_id'), table_name='article_entities')
    op.drop_index(op.f('ix_article_entities_article_id'), table_name='article_entities')
    op.drop_table('article_entities')
    op.drop_index(op.f('ix_article_categories_category_id'), table_name='article_categories')
    op.drop_index(op.f('ix_article_categories_article_id'), table_name='article_categories')
    op.drop_table('article_categories')
    op.drop_index(op.f('ix_analytical_scores_article_id'), table_name='analytical_scores')
    op.drop_table('analytical_scores')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
